export const CHANGE_CURRENT_INDEX='changeCurrentIndex'
export const ADD_VOTE_THEME='addVoteTheme'
export const ADD_VOTE_OPTION='addVoteOption'
export const ADD_VOTE_EXTRA_INFO='addVoteExtraInfo'
export const SUBMIT_VOTE='submitVote'